
name: Go Scraper Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'  # Adjust to your Go version

      - name: Install dependencies
        run: go mod tidy

      - name: Run scraper
        run: go run cmd/scraper/main.go
